### ISSUE TITLE
Is the model type after finetune pytorch (*.pt) or tensorflow (*.tf) ?

### ISSUE THREAD

**Issue by ITHealer** [HKAB/whisper-finetune-1-notebook#1]

**Comment by HKAB** [comment]
Have a look at: https://huggingface.co/hkab/whisper-base-vietnamese-finetuned/tree/main. The weight is for Pytorch. If you want to use Tensorflow, might be you could try somehow convert the weight and load with `TFWhisperForConditionalGeneration`, I've never tried this.
